/**:
  ros__parameters:
    # Joy Driver Parameters
    linear_x_scale: 2.0
    linear_y_scale: 2.0
    angular_scale: 2.0
    linear_x_axis: 1
    linear_y_axis: 0
    angular_axis: 2
    Kp: 1.0

    # Mecanum Wheel Controller Parameters
    wheel_radius: 0.08
    wheel_base_x: 0.148
    wheel_base_y: 0.200
    serial_port: "/dev/ttyACM0"
    baud_rate: 115200
    motor_ids: [1, 2, 3, 4]  # FL, FR, BL, BR
