/**:
  ros__parameters:
    # Joy Driver Parameters
    linear_x_scale: 1.0
    linear_y_scale: 1.0
    angular_scale: 1.0
    linear_x_axis: 1
    linear_y_axis: 0
    angular_axis: 3

    # Mecanum Wheel Controller Parameters
    wheel_radius: 0.1
    wheel_base_x: 0.5
    wheel_base_y: 0.5
    serial_port: "/dev/ttyACM1"
    baud_rate: 115200
    motor_ids: [1, 2, 3, 4]  # FL, FR, BL, BR
